### PR TITLE
style: run cargo fmt on whole codebase

### PR DESCRIPTION
**Pull request by bortyr**
Runnig cargo fmt on our codebase will make the code more standardized with the rust community guidelines (on which cargo fmt is based)

We could look into running cargo fmt on every commit as git hook/action. 

If we would like a certain piece of code not to be changed by the cargo fmt, we could insert a #[rustfmt::skip] line before.

Treat this draft of PR more of a nice way to see how the codebase would change and what it would look like

### CODE REVIEW

**Comment by calebbourg** [comment]
I like the idea of going with style conventions that `cargo` enforces

**Comment by jhodapp** [comment]
Same here, I'm open to merging this PR and then getting cargo fmt in place to always format on push or commit.

**Review by jhodapp — CHANGES_REQUESTED** [review]
Let's merge my two open PRs and then update and land this PR. Sound good @bortyr ?

**Comment by bortyr** [comment]
> Let's merge my two open PRs and then update and land this PR. Sound good @bortyr ?

Sounds good

**Review by jhodapp — APPROVED** [review]
Look great, I really like how `cargo fmt` cleans things up and the style it uses. I also verified this still compiles and runs as expected.

**Pull request merged**
